{
 "title": "HostMetrics",
 "description": "OpenTelemetry Collector otelcol-contrib hostmetrics",
 "tags": [
  "linux",
  "otelcol-contrib",
  "opentelemetry"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host_name",
    "label": "host",
    "query": {
     "query": "label_values(system_uptime_seconds,host_name)"
    }
   },
   {
    "name": "mountpoint",
    "query": {
     "query": "label_values(system_filesystem_usage_bytes{host_name=\"$host_name\"},mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Up",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "floor(increase(system_uptime_seconds{host_name=\"$host_name\"}[1m])/59.9)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Physical CPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_physical_count{host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logical CPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_logical_count{host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time (stacked, no idle)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "sum by (state) (irate(system_cpu_time_seconds_total{host_name=\"$host_name\",state!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization (stacked, no idle)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "sum by (state) (system_cpu_utilization_ratio{host_name=\"$host_name\",state!=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit_bytes{host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Page Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_page_size_bytes{host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (state) (system_memory_usage_bytes{host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{host_name=\"$host_name\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_linux_memory_available_bytes{host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Dirty",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_linux_memory_dirty_bytes{host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (system_network_connections{host_name=\"$host_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_network_conntrack_count{host_name=\"$host_name\"}",
     "legendFormat": "Count"
    },
    {
     "expr": "system_network_conntrack_max{host_name=\"$host_name\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Packet Transmit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_network_packets_total{host_name=\"$host_name\",direction=\"transmit\",device!~\"lo|ovs-system\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packet Receive",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_network_packets_total{host_name=\"$host_name\",direction=\"receive\",device!~\"lo|ovs-system\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bytes Transmit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(system_network_io_bytes_total{host_name=\"$host_name\",direction=\"transmit\",device!~\"lo|ovs-system\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bytes Receive",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(system_network_io_bytes_total{host_name=\"$host_name\",direction=\"receive\",device!~\"lo|ovs-system\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packet Transmit Dropped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_network_dropped_total{host_name=\"$host_name\",direction=\"transmit\",device!~\"lo|ovs-system\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packet Receive Dropped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_network_dropped_total{host_name=\"$host_name\",direction=\"receive\",device!~\"lo|ovs-system\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packet Transmit Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_network_errors_total{host_name=\"$host_name\",direction=\"transmit\",device!~\"lo|ovs-system\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packet Receive Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_network_errors_total{host_name=\"$host_name\",direction=\"receive\",device!~\"lo|ovs-system\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Bytes Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(system_disk_io_bytes_total{host_name=\"$host_name\",direction=\"read\",device!~\".*[0-9]\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bytes Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(system_disk_io_bytes_total{host_name=\"$host_name\",direction=\"write\",device!~\".*[0-9]\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Operations Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_disk_operations_total{host_name=\"$host_name\",direction=\"read\",device!~\".*[0-9]\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Operations Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(system_disk_operations_total{host_name=\"$host_name\",direction=\"write\",device!~\".*[0-9]\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Operations Read Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(system_disk_operation_time_seconds_total{host_name=\"$host_name\",direction=\"read\",device!~\".*[0-9]\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Operations Write Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(system_disk_operation_time_seconds_total{host_name=\"$host_name\",direction=\"write\",device!~\".*[0-9]\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IO Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(system_disk_io_time_seconds_total{host_name=\"$host_name\",device!~\".*[0-9]\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  irate(system_disk_weighted_io_time_seconds_total{host_name=\"$host_name\",device!~\".*[0-9]\"}[$__rate_interval])\n  /\n  irate(system_disk_io_time_seconds_total{host_name=\"$host_name\",device!~\".*[0-9]\"}[$__rate_interval])\n)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Operations Pending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_disk_pending_operations{host_name=\"$host_name\",device!~\".*[0-9]\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Filesystem Usage ($mountpoint)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "repeat": "mountpoint",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes{host_name=\"microshift\",state=\"used\",mountpoint=\"$mountpoint\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(system_filesystem_usage_bytes{host_name=\"microshift\",mountpoint=\"$mountpoint\"})",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "system_processes_count{host_name=\"$host_name\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Process Creation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "irate(system_processes_created_total{host_name=\"$host_name\"}[$__rate_interval])",
     "legendFormat": "new"
    }
   ]
  }
 ]
}